DROP DATABASE IF EXISTS todolist;
CREATE DATABASE IF NOT EXISTS todolist CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
USE todolist;
CREATE USER IF NOT EXISTS 'todolist'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON todolist.* TO 'todolist'@'localhost';
FLUSH PRIVILEGES;
CREATE TABLE todos (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, task VARCHAR(255) NOT NULL );